/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package moleculeInformationCard;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JTextField;
import org.gephi.graph.api.Edge;
import org.gephi.graph.api.Graph;
import org.gephi.graph.api.Node;

/**
 *
 * @author alex
 */
public class NodeInformationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NodeInformation
     *
     * @param edge
     */
    
    private Node node;
    private Graph graph;

    public JTextField getSimilarityTextField() {
        return similarityTextField;
    }

    public void setSimilarityTextField(JTextField similarityTextField) {
        this.similarityTextField = similarityTextField;
    }
    
    public NodeInformationJPanel(Edge edge, Node node, Graph graph) {
        initComponents();
        
        this.node = edge.getTarget().equals(node) ? edge.getSource() : edge.getTarget();

        this.smilesTextField.setText((String) this.node.getId());
        this.chemblIdTextField.setText(this.node.getLabel());
        this.similarityTextField.setText(String.valueOf(edge.getWeight()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        smilesTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        chemblIdTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        similarityTextField = new javax.swing.JTextField();
        moleculeInfoButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        setPreferredSize(new java.awt.Dimension(583, 50));
        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("SMILES: "); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel1, gridBagConstraints);

        smilesTextField.setEditable(false);
        smilesTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        smilesTextField.setText(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 1, 5, 5);
        add(smilesTextField, gridBagConstraints);

        jLabel2.setText("ChEMBL ID: "); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel2, gridBagConstraints);

        chemblIdTextField.setEditable(false);
        chemblIdTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        chemblIdTextField.setText(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 1, 5, 5);
        add(chemblIdTextField, gridBagConstraints);

        jLabel3.setText("Similarity: "); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel3, gridBagConstraints);

        similarityTextField.setEditable(false);
        similarityTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        similarityTextField.setText(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 1, 5, 5);
        add(similarityTextField, gridBagConstraints);

        moleculeInfoButton.setText("Molecule Info."); // NOI18N
        moleculeInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moleculeInfoButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(moleculeInfoButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void moleculeInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moleculeInfoButtonActionPerformed
        // TODO add your handling code here:
        MoleculeInformationJPanel card = new MoleculeInformationJPanel(
                node,
                graph,
                false
        );

        JFrame frame = new JFrame();
        frame.setLayout(new BorderLayout());
        frame.add(card);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_moleculeInfoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chemblIdTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton moleculeInfoButton;
    private javax.swing.JTextField similarityTextField;
    private javax.swing.JTextField smilesTextField;
    // End of variables declaration//GEN-END:variables
}
