/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package initApp;

import centralForm.CentralForm;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author alex
 */
public class SelectFileForm extends javax.swing.JFrame {

    /**
     * Creates new form SelectFileForm
     */
    public SelectFileForm() {
        initComponents();

        this.layoutComboBox.addItem("Fruchterman Reingold");
        this.layoutComboBox.addItem("Force Atlas");
        this.layoutComboBox.addItem("YifanHu");
        this.layoutComboBox.setSelectedIndex(0);

        this.currenteNewProjectPath = System.getProperty("user.home");
        this.currenteOpenProjectPath = System.getProperty("user.home");

    }

    private String filePathSelect;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openProjectBtn = new javax.swing.JButton();
        newProjectBtn = new javax.swing.JButton();
        layoutComboBox = new javax.swing.JComboBox<>();
        newProjectTextField = new javax.swing.JTextField();
        openProjectTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        confirmBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        layoutTimeTextField = new javax.swing.JTextField();
        thresholdTextField = new javax.swing.JTextField();
        informationalFileTextField = new javax.swing.JTextField();
        informationalFileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GraphLecules"); // NOI18N
        setBackground(new java.awt.Color(153, 153, 153));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);

        openProjectBtn.setText("Open Project"); // NOI18N
        openProjectBtn.setToolTipText("The .gexf file from a saved project"); // NOI18N
        openProjectBtn.setPreferredSize(new java.awt.Dimension(140, 24));
        openProjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openProjectBtnActionPerformed(evt);
            }
        });

        newProjectBtn.setText("New Project"); // NOI18N
        newProjectBtn.setToolTipText("The .cvs file to initialize a new project"); // NOI18N
        newProjectBtn.setPreferredSize(new java.awt.Dimension(140, 24));
        newProjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProjectBtnActionPerformed(evt);
            }
        });

        layoutComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layoutComboBoxActionPerformed(evt);
            }
        });

        newProjectTextField.setEditable(false);
        newProjectTextField.setText(""); // NOI18N
        newProjectTextField.setMaximumSize(new java.awt.Dimension(64, 24));

        openProjectTextField.setEditable(false);
        openProjectTextField.setText(""); // NOI18N
        openProjectTextField.setMaximumSize(new java.awt.Dimension(64, 24));

        jLabel1.setText("Network Layout: "); // NOI18N

        jLabel2.setText("Layout Time (seconds): "); // NOI18N

        confirmBtn.setText("Confirm"); // NOI18N
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Initial Threshold: "); // NOI18N

        layoutTimeTextField.setColumns(13);
        layoutTimeTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        layoutTimeTextField.setText(""); // NOI18N
        layoutTimeTextField.setToolTipText("The time spent on the layout modeling."); // NOI18N
        layoutTimeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layoutTimeTextFieldActionPerformed(evt);
            }
        });

        thresholdTextField.setColumns(13);
        thresholdTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        thresholdTextField.setText(""); // NOI18N
        thresholdTextField.setToolTipText("A value from 0 to 1. If the similarity value is greater than or equal to, then the edge will be created."); // NOI18N

        informationalFileTextField.setEditable(false);
        informationalFileTextField.setText(""); // NOI18N
        informationalFileTextField.setMaximumSize(new java.awt.Dimension(64, 24));

        informationalFileButton.setText("Informational File"); // NOI18N
        informationalFileButton.setEnabled(false);
        informationalFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informationalFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(layoutComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(layoutTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(newProjectTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(openProjectTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(informationalFileTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(confirmBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(openProjectBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newProjectBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(informationalFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newProjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(openProjectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211)
                        .addComponent(confirmBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newProjectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(openProjectTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(informationalFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(informationalFileButton))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(layoutComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(layoutTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(thresholdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String currenteOpenProjectPath = "";

    private void openProjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openProjectBtnActionPerformed
        // TODO add your handling code here:
        SelectFileControl selectFileControl = new SelectFileControl();

        selectFileControl.openProject(this, this.currenteOpenProjectPath);
        this.openProjectTextField.setText(selectFileControl.getOpenProjectPath() != null && !selectFileControl.getOpenProjectPath().isBlank() ? selectFileControl.getOpenProjectPath() : this.openProjectTextField.getText());

        if (this.openProjectTextField.getText() != null && !this.openProjectTextField.getText().isBlank()) {
            this.currenteOpenProjectPath = new File(this.openProjectTextField.getText()).getParent();
            this.newProjectTextField.setText("");
            this.informationalFileButton.setEnabled(true);
            this.filePathSelect = this.openProjectTextField.getText();
        }
    }//GEN-LAST:event_openProjectBtnActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        this.confirmBtn.setEnabled(false);

        Long numberLayoutTime = 0l;
        try {
            // Tentamos converter o valor para um número
            numberLayoutTime = Long.valueOf(this.layoutTimeTextField.getText());

            if (numberLayoutTime <= 0) {
                JOptionPane.showMessageDialog(this, "Please enter a valid number in the field: Layout Time (seconds).", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

        } catch (NumberFormatException ex) {
            // Tratamento de erro se o usuário inserir algo que não seja um número
            JOptionPane.showMessageDialog(this, "Please enter a valid number in the field: Layout Time (seconds).", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        float numberThreshold = 0f;
        try {
            // Tentamos converter o valor para um número
            numberThreshold = Float.parseFloat(this.thresholdTextField.getText());

            if (numberThreshold < 0 || numberThreshold > 1) {
                JOptionPane.showMessageDialog(this, "Please enter a valid number in the field: Initial Threshold.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

        } catch (NumberFormatException ex) {
            // Tratamento de erro se o usuário inserir algo que não seja um número
            JOptionPane.showMessageDialog(this, "Please enter a valid number in the field: Initial Threshold.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if ((this.openProjectTextField.getText() == null || this.openProjectTextField.getText().isBlank())
                && (this.newProjectTextField.getText() == null || this.newProjectTextField.getText().isBlank())) {
            JOptionPane.showMessageDialog(this, "Please choose a .csv file to load a new project or a .gexf file to open a project.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (this.openProjectTextField.getText() != null && !this.openProjectTextField.getText().isBlank()
                && (this.informationalFileTextField.getText() == null || this.informationalFileTextField.getText().isBlank())) {
            JOptionPane.showMessageDialog(this, "The molecule information file was not inserted, so it will not be possible to load the information card correctly.", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }

        System.out.println("Initial Threshold: " + numberThreshold);
        System.out.println("Layout time: " + numberLayoutTime);
        System.out.println("File Path: " + ((this.openProjectTextField.getText() == null || this.openProjectTextField.getText().isBlank()) ? this.newProjectTextField.getText() : this.openProjectTextField.getText()));
        System.out.println("Informational File Path: " + this.informationalFileTextField.getText());

        CentralForm centralForm = new CentralForm();
        centralForm.init(this.layoutComboBox.getSelectedIndex(), numberLayoutTime, numberThreshold, this.filePathSelect, this.informationalFileTextField.getText());
        this.setVisible(false);
        centralForm.setVisible(true);
        this.confirmBtn.setEnabled(true);
    }//GEN-LAST:event_confirmBtnActionPerformed

    private String currenteNewProjectPath = "";

    private void newProjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProjectBtnActionPerformed
        // TODO add your handling code here:
        SelectFileControl selectFileControl = new SelectFileControl();

        selectFileControl.newProject(this, this.currenteNewProjectPath);
        this.newProjectTextField.setText(selectFileControl.getNewProjectPath() != null && !selectFileControl.getNewProjectPath().isBlank() ? selectFileControl.getNewProjectPath() : this.newProjectTextField.getText());

        if (this.newProjectTextField.getText() != null && !this.newProjectTextField.getText().isBlank()) {
            this.currenteNewProjectPath = new File(this.newProjectTextField.getText()).getParent();
            this.openProjectTextField.setText("");
            this.informationalFileTextField.setText("");
            this.informationalFileButton.setEnabled(false);
            this.filePathSelect = this.newProjectTextField.getText();
        }
    }//GEN-LAST:event_newProjectBtnActionPerformed

    private void layoutComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layoutComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_layoutComboBoxActionPerformed

    private void layoutTimeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layoutTimeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_layoutTimeTextFieldActionPerformed

    private String currenteInformationalFilePath = "";

    private void informationalFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informationalFileButtonActionPerformed
        // TODO add your handling code here:
        SelectFileControl selectFileControl = new SelectFileControl();

        selectFileControl.informationalFile(this, this.currenteInformationalFilePath);
        this.informationalFileTextField.setText(selectFileControl.getInformationalFilePath() != null && !selectFileControl.getInformationalFilePath().isBlank() ? selectFileControl.getInformationalFilePath() : this.informationalFileTextField.getText());

        if (this.informationalFileTextField.getText() != null && !this.informationalFileTextField.getText().isBlank()) {
            this.currenteInformationalFilePath = new File(this.informationalFileTextField.getText()).getParent();
        }
    }//GEN-LAST:event_informationalFileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectFileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectFileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectFileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectFileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectFileForm form = new SelectFileForm();
                form.setLocation((Toolkit.getDefaultToolkit().getScreenSize().width - form.getWidth()) / 2, (Toolkit.getDefaultToolkit().getScreenSize().height - form.getHeight()) / 2);
                form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmBtn;
    private javax.swing.JButton informationalFileButton;
    private javax.swing.JTextField informationalFileTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> layoutComboBox;
    private javax.swing.JTextField layoutTimeTextField;
    private javax.swing.JButton newProjectBtn;
    private javax.swing.JTextField newProjectTextField;
    private javax.swing.JButton openProjectBtn;
    private javax.swing.JTextField openProjectTextField;
    private javax.swing.JTextField thresholdTextField;
    // End of variables declaration//GEN-END:variables
}
